# Generated by Django 5.2.1 on 2025-06-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalansoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='titre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
