# Generated by Django 5.2.3 on 2025-06-25 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalansoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptMemoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_taxonomie', models.CharField(max_length=50)),
                ('prompt', models.TextField()),
                ('retour_enseignant', models.TextField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalansoapp.cours')),
            ],
        ),
    ]
