# Generated by Django 5.2.3 on 2025-07-12 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalansoapp', '0002_promptmemoire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_AI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title', models.CharField(max_length=255)),
                ('quiz_description', models.CharField(max_length=255)),
                ('total_score', models.IntegerField(blank=True, null=True)),
                ('max_score', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='kalansoapp.cours')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizz', to='kalansoapp.module')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, default=True)),
                ('question_text', models.CharField(max_length=1000)),
                ('options', models.JSONField(blank=True, null=True)),
                ('required_time', models.FloatField(default=60)),
                ('user_answer', models.CharField(blank=True, max_length=500, null=True)),
                ('great_answer', models.CharField(max_length=500)),
                ('score', models.FloatField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='kalansoapp.quiz_ai')),
            ],
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
