# Generated by Django 5.2.1 on 2025-06-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalansoapp', '0002_exercice_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
