# Generated by Django 5.2.3 on 2025-07-12 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalansoapp', '0003_quiz_ai_questionanswers_delete_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_ai',
            name='questions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionanswers',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_quiz', to='kalansoapp.quiz_ai'),
        ),
    ]
