# Generated by Django 5.2.1 on 2025-06-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalansoapp', '0003_cours_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
